name: Biuud

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
     
      - name: Set Python Encoding
        run: python -c "import sys; sys.stdout.reconfigure(encoding='utf-8')"
      - name: Install dependencies
        run: |
          python -m pip install ping3 ctypes

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'GoogleTranslatefix.py'
          upload_exe_with_name: 'GoogleTranslatefix'
          options: --onefile, --name "GoogleTranslatefix"
